name: learning
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.4



  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.7.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/i18n/
    - assets/json/

#  fonts:
#    - family: IBMPlexSans
#      fonts:
#        - asset: assets/fonts/IBMPlexSans-Bold.ttf
#          weight: 600
#        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
#          weight: 600
#        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
#          weight: 600
#        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
#          weight: 600
#        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf
#          weight: 600
#        - asset: assets/fonts/IBMPlexSans-Italic.ttf
#          weight: 600
#        - asset: assets/fonts/IBMPlexSans-Light.ttf
#          weight: 600
#        - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
#          weight: 600
#        - asset: assets/fonts/IBMPlexSans-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
#          weight: 500
#        - asset: assets/fonts/IBMPlexSans-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/IBMPlexSans-Thin.ttf
#          weight: 400
#        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
#          weight: 400